import {
  shirt1,
  shirt2,
  shirt3,
  shirt4,
  shirt5,
  shirt6,
  shirt7,
  shirt8,
  shirt9,
  shirt10,
  tshirt3,
  tshirt2,
  tshirt4,
  tshirt1,
} from "./constant";

let info = [
  {
    id: "1",
    name: "multi Astronout T-shirt",
    amount: 80,
    image: shirt1,
    image1: shirt1,
    image2: shirt2,
    image3: shirt3,
    image4: shirt4,
  },
  {
    id: "2",
    name: "nike",
    amount: 224,
    image: shirt2,
    image1: shirt5,
    image2: shirt6,
    image3: shirt7,
    image4: shirt8,
  },
  {
    id: "3",
    name: "spider",
    amount: 331,
    image: shirt3,
    image1: shirt9,
    image2: shirt1,
    image3: shirt2,
    image4: shirt4,
  },
  {
    id: "4",
    name: "unico Astronout T-shirt",
    amount: 132,
    image: shirt4,
    image1: shirt1,
    image2: shirt10,
    image3: shirt5,
    image4: shirt3,
  },
];

let information = [
  {
    id: "5",
    name: "multi Astronout T-shirt",
    amount: 80,
    image: shirt5,
    image1: shirt1,
    image2: shirt2,
    image3: shirt3,
    image4: shirt4,
  },
  {
    id: "6",
    name: "Astronout T-shirt",
    amount: 94,
    image: shirt6,
    image1: shirt5,
    image2: shirt6,
    image3: shirt7,
    image4: shirt8,
  },
  {
    id: "7",
    name: "spider T-shirt",
    amount: 111,
    image: shirt7,
    image1: shirt9,
    image2: shirt1,
    image3: shirt2,
    image4: shirt4,
  },
  {
    id: "8",
    name: "captain",
    amount: 222,
    image: shirt8,
    image1: shirt1,
    image2: shirt10,
    image3: shirt5,
    image4: shirt3,
  },
];

let information2 = [
  {
    id: "9",
    name: "multi Astronout T-shirt",
    amount: 70,
    image: tshirt3,
    image1: shirt1,
    image2: shirt2,
    image3: shirt3,
    image4: shirt4,
  },
  {
    id: "10",
    name: "naruto",
    amount: 44,
    image: tshirt4,
    image1: shirt5,
    image2: shirt6,
    image3: shirt7,
    image4: shirt8,
  },
  {
    id: "11",
    name: "black panther",
    amount: 311,
    image: tshirt2,
    image1: shirt9,
    image2: shirt1,
    image3: shirt2,
    image4: shirt4,
  },
  {
    id: "12",
    name: "new unico",
    amount: 422,
    image: tshirt1,
    image1: shirt1,
    image2: shirt10,
    image3: shirt5,
    image4: shirt3,
  },
];

export { info, information2, information };
